### ISSUE TITLE
Meetup Event Checklist

### ISSUE THREAD

**Issue by jazzyfresh** [GitHub-Users-Groups/SoCal-GUG#11]
a TODO list of all things that are necessary for a meetup, including
- preparation
- day-of-event setup
- during-the-event logistics
- postprocessing

**Comment by ctrlaltdev** [comment]
Oh, and once this list set, we can make an issue template out of it, for future meetups organization.
I'll start and state the obvious, unordered:

GitHub / meetup.org side:
- [ ] Create the meetup on meetup.org
- [ ] Create the meetup file in [events/](https://github.com/GitHub-Users-Groups/SoCal-GUG/tree/master/events)
- [ ] Create or update the venue file in [venues/](https://github.com/GitHub-Users-Groups/SoCal-GUG/tree/master/venues)
- [ ] Update README.md with the next meetup
- [ ] Find (a) speaker(s)
- [ ] Ask for a title and a summary of the talk
- [ ] Ask for a picture and a speaker bio (optional)

Venue side:
- [ ] Find a venue
- [ ] Check with security/safety personnel the conditions for hosting an running the event
- [ ] Get some public WiFi
- [ ] Get a projector and a screen or white surface
- [ ] Get mics and speakers
- [ ] Locate and point the direction to bathrooms
- [ ] Order food and drinks
- [ ] Arrange the furniture before the event
- [ ] Rearrange the furniture after the event
- [ ] Cleanup

**Comment by ravigadhia** [comment]
@ctrlaltdev, great list.  You clearly have some experience running meetups!

Adding to your excellent list, from my perspective, it looks kind of as follows:

Scheduling:
- Triangulate across 
[ ] Venues & corresponding dates that work 
[ ] Speakers & corresponding dates that work
[ ] Hosts (GitHub staff & group organizers) & corresponding dates that work 

Marketing:
- For each speaker, collect talk title, talk abstract, and speaker bio
- For venue, collect company description, location, parking 
- Create Meetup Page
- Create GitHub Users' Group event, venue, speaker pages
- Post to Twitter & LinkedIn, tagging GitHub, speaker, speaker employer, venue company

Planning
- Order Food & Drink (either organizer, venue host, or speaker, depending on sponsorship arrangement)
  - Double check venue alcohol policy
- Make sure venue has projector, amplified sound & microphones.
  - Arrange for on-site tech support, or venue host should learn how to use equipment and receive written instructions
- Double check speaker travel schedule
- Remind GitHub staff attendee to bring GitHub swag as speaker gift & stickers for attendees.

Execution
- Venue host co-ordinates room logistics
- Meetup organizer arrives early enough to double check everything welcome speaker, etc.
- Set out name tags
- Set out sign in sheet (used only to confirm # of attendees)
- Venue host & organizers should try to meet all attendees and facilitate networking before speaker content
- Someone should moderate discussion (should this be determined ahead of time)
  - Talk about ideas & interests for next meetup
  - Lead a retrospective

Follow-up
- Thank speakers via e-mail
- Adjust this repo's content to reflect Meetup has passed.

That's a first pass. I'll iterate on the above as more comes to mind.
